---
 - hosts: all

   gather_facts: no
   remote_user: root
 
   tasks:
   - setup:
#   - name: Install fail2ban
#     yum:
#       name: fail2ban
#       state: present
#   - service:
#       name: fail2ban
#       ensure: started
   - name: Add a new user named provision
     user:
          name=provision

 
   - name: Add provision user to the sudoers
     copy:
          dest: "/etc/sudoers.d/provision"
          content: "provision  ALL=(ALL)  NOPASSWD: ALL"
 
   - name: Deploy SSH Key - Evan
     authorized_key: user=provision
                     key="{{ lookup('file', '/home/evan/.ssh/id_rsa.pub') }}"
                     state=present
   - name: Deploy SSH Key - Provision (2.chaneybros.com)
     authorized_key: user=provision
                     key="{{ lookup('file', '/home/evan/ansible/2.chaneybros.com-provision.pub') }}"
                     state=present
   - name: Disable Password Authentication
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes
     notify:
       - restart ssh
 
   - name: Disable Root Login
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
     notify:
       - restart ssh
   - name: upgrade all packages
     yum:
       name: '*'
       state: latest
 
   handlers:
   - name: restart ssh
     service:
       name=sshd
       state=restarted
