---
 - hosts: all

   remote_user: provision
   become: yes
   become_method: sudo

   vars:
     certbot_create_if_missing: true
     certbot_install_from_source: true
     certbot_create_method: standalone
     certbot_create_standalone_stop_services: []
     certbot_certs:
       - domains:
           - "{{ inventory_hostname }}"
     certbot_admin_email: evanachaney@gmail.com
     certbot_auto_renew: true
     certbot_auto_renew_hour: 3
     certbot_auto_renew_minute: 30
     certbot_auto_renew_options: "--quiet --no-self-upgrade"
   roles:
     - geerlingguy.git
     - geerlingguy.certbot
   tasks:
     - name: "Install docker"
       yum:
         name: docker
         state: present
     - service:
         name: docker
         state: started
     - name: "Install EPEL"
       yum:
         name: epel-release
         state: present
     - name: "Install pip2"
       yum:
         name: python2-pip
         state: present
     - name: "Install docker pip module"
       pip:
         name: docker
     - sysctl:
         name: fs.file-max
         value: 65536
         state: present
     - sysctl:
         name: vm.max_map_count
         value: 262144
         state: present
     - name: Set up sonar docker container
       docker_container:
         name: Sonarqube
         image: sonarqube
         state: started
         stop_timeout: 3600
         ports:
           "9000:9000"
     - name: Install  Apache
       yum:
         name: httpd
         state: present
     - name: Start service httpd, if not started
       service:
         name: httpd
         state: started

