---
 - hosts: all
   become: yes
   become_method: sudo
   tasks:

   - setup:


     # Install packages
   - name: upgrade all packages (RH)
     yum:
       name: '*'
     when: ansible_os_family == "RedHat"

   - name: upgrade all packages (Debian)
     apt:
       name: '*'
       state: latest
     when: ansible_os_family == "Debian"